### ISSUE TITLE
App crash on android

### ISSUE THREAD

**Issue by bdndreams** [snipsco/snips-platform-android-demo#7]
09-04 15:57:17.068 13247-13709/ai.snips.snipsdemo E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2208)
09-04 15:57:17.108 13247-13709/ai.snips.snipsdemo E/SnipsPlatform: Could not send message to Snips platform: Transaction failed on small parcel; remote process probably died
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.os.IMessenger$Stub$Proxy.send(IMessenger.java:89)
        at android.os.Messenger.send(Messenger.java:57)
        at ai.snips.platform.SnipsPlatformClient$RemoteServiceImpl.send(SnipsPlatformClient.kt:242)
        at ai.snips.platform.SnipsPlatformClient.sendAudioBuffer(SnipsPlatformClient.kt:531)
        at ai.snips.snipsdemo.MainActivity.runStreaming(MainActivity.java:288)
        at ai.snips.snipsdemo.MainActivity.access$300(MainActivity.java:43)
        at ai.snips.snipsdemo.MainActivity$11.run(MainActivity.java:271)
09-04 15:57:17.113 13247-13247/ai.snips.snipsdemo E/SnipsPlatform: Snips processing service disconnected, attempting a reconnect
09-04 15:57:21.318 13247-13247/ai.snips.snipsdemo E/SnipsPlatform: Snips processing service disconnected, attempting a reconnect

**Comment by thanksmister** [comment]
I think this occurs because you have the a missing assistant or the assistant you moved to the device is in the wrong location.  

Did you upload your unzipped assistant files to the correct device location and proper directory name?

**Comment by bdndreams** [comment]
Files are on proper location,  i have also check on debug mode, files are loaded properly.

**Comment by thanksmister** [comment]
Make sure you check out the latest version, there was a version change 7 days ago to 0.58.3.  If you don't have that version of Snips then new assistants won't work.  Check that you do have the folder in the correct location by ding "adb shell" then navigate to the snips_android_assistant.   

The assumption is from the installation instructions that the location of the external storage is always "sdcard" but on some devices this could be different.  You can check which directory your device uses for external storage by logging the output fo the directory in the code "Log.d("ManActivity", Environment.getExternalStorageDirectory().toString());".   

This location should be the same as the location where your "snips_android_assistant" folder is located. If it's not then you can either move the "snips_android_assistant" to that location on your device or manually change the location to the sdcard by doing something like this:

File assistantDir = new File("sdcard/", "snips_android_assistant");

**Comment by thanksmister** [comment]
Just to be sure you could also trace out the location of your external storage on the device to be sure it matches the assistant directory.  Log.d("ManActivity", Environment.getExternalStorageDirectory().toString());

**Comment by thanksmister** [comment]
This is duplicate of https://github.com/snipsco/snips-issues/issues/22.
